### ISSUE TITLE
Error import/export

### ISSUE THREAD

**Issue by NoraNiemeyer** [CodersCare/l10nmgr#1]
We have installed the current version for testing under TYPO3 11.5.16.
Default language is German.

During import and export the following problems occur:
During XML export a PHP error occurs when I select another language under Alternative source language.
If I already choose another language in the configuration, the XML file still contains the default language German.
A PHP error also occurs during the import.

**Comment by Cybercraft-GmbH** [comment]
Hi Nora - the problem's you faced are due to the fact that this is not the early access repository but the public one. Please use the early access you've got as a sponsor via your company and checkout the master from the private repository.

So I will close the issue here.

**Comment by NoraNiemeyer** [comment]
We have installed the version from the private repository

**Comment by Cybercraft-GmbH** [comment]
OK - so if you've got issues with that version, please report them in the issue tracker there to avoid confusion.
