### ISSUE TITLE
PHP warning on import: undefined array key "pi_flexform" 

### ISSUE THREAD

**Issue by derBoogie** [CodersCare/l10nmgr#32]
After the update of l10nmgr to version 1.0.0 with TYPO3 11.5.29 I'm getting multiple PHP warnings at import: undefined array key "pi_flexform" in ../l10nmgr/Classes/Model/L10nBaseService.php line 792.

**Comment by Konafets** [comment]
Duplicate of https://github.com/CodersCare/l10nmgr/issues/29
