### ISSUE TITLE
v12: Typed property 

### ISSUE THREAD

**Issue by ikonplant** [CodersCare/l10nmgr#43]
- TYPO3 v12
- PHP 8.2.14
- $GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = true

Open l10nmgr module =>

`Typed property Localizationteam\L10nmngr\View\L10nHtmlListView::$sysLang must not be accessed before initialization`

**Comment by plan2github** [comment]
Updated: reported in v12 repository https://github.com/CodersCare/l10nmgr_EA/issues/68
