### ISSUE TITLE
TYPO3 v12 compatibility 

### ISSUE THREAD

**Issue by mrk131324** [CodersCare/l10nmgr#44]
Are there already plans or a timeline for making l10n_mgr work with TYPO3v12?

**Comment by PetraCyber** [comment]
Hi Martin,

Good news! There's already an l10nmgr version that works with TYPO3 Version 12. It is available in the Early Access Repository on GitHub as part of the Coders Care initiative.
 
https://coders.care/for/crowdfunding/l10nmgr-and-localizer

Those who support us in developing and maintaining this extension get access to this repository and can use the version.

Supporters get access to the l10nmgr for Version 12, and if you encounter any issues, you can report them in the Early Access Repository.

So, yes, we have a working l10nmgr for TYPO3 Version 12. To keep up with future releases and maintenance, we appreciate any support, even just a couple of hours would be fantastic.

I hope this helps!
