### ISSUE TITLE
TYPO3 v11 & v12 Support

### ISSUE THREAD

**Issue by rialDave** [CodersCare/l10nmgr#6]
Hi,

what are the current plans for supporting TYPO3 v11 and v12? Are there any planned releases regarding this?

**Comment by Bunnyfield** [comment]
For version 11 there is an early-access-repository available for sponsors of our crowd funding campaign, which you can find here
https://coders.care/for/crowdfunding/l10nmgr-and-localizer/support

The version 11 in there is already compatible to both CMS 10 and CMS 11 at the same time and supports PHP 7.5, 8.0 and 8.1

We are planning to do a similar campaign for CMS 12 too, so most likely there will be an L10nmgr version 12 supporting CMS 11 and 12.
