### ISSUE TITLE
XML Export/Import: Checkboxes can't be checked/unchecked

### ISSUE THREAD

**Issue by loctimize-yvonne** [CodersCare/l10nmgr#7]
When I tried to export the content of a single page from TYPO3 via the L10N manager (v. 10.2.1), I noticed that these two options cannot be selected or deselected:

![L10N-Manager Bug](https://user-images.githubusercontent.com/79167066/227938229-2a4fe692-6c6d-49a7-b386-0327db5a4f56.png)

**Comment by Bunnyfield** [comment]
Fixed in current master and 11-0 branch
